### ISSUE TITLE
end-to-end example broken with Bazel 0.28.0

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/examples#105]
The end-to-end example is broken on all platforms: https://buildkite.com/bazel/bazel-bazel-examples/builds/54#8289092a-377c-4687-9ce8-770792a3ae87

```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/1c525a110a1039d4941eb4a8d5fde578/external/io_bazel_rules_appengine/appengine/appengine.bzl:72:16: name 'FileType' is not defined
--
  | ERROR: error loading package '': Extension 'appengine/appengine.bzl' has errors
  | Traceback (most recent call last):
  | File "bazelci.py", line 2778, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 2758, in main
  | bazel_version=task_config.get("bazel") or configs.get("bazel"),
  | File "bazelci.py", line 794, in execute_commands
  | bazel_version = print_bazel_version_info(bazel_binary, platform)
  | File "bazelci.py", line 1006, in print_bazel_version_info
  | + ["--nomaster_bazelrc", "--bazelrc=/dev/null", "info"]
  | File "bazelci.py", line 1623, in execute_command
  | args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  | File "/usr/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['bazel', '--nomaster_bazelrc', '--bazelrc=/dev/null', 'info']' returned non-zero exit status 2.
```

Culprit: `@io_bazel_rules_appengine//appengine/appengine.bzl` uses deprecated type `FileType` that was removed in Bazel 0.28.0.

**Comment by jin** [comment]
Fixed with https://github.com/bazelbuild/examples/pull/108
