### ISSUE TITLE
Cannot build Android Firebase example on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/examples#146]
Broken at 84f298060b00f37924495ba4d8cbde1ff6d8e969 with Bazel 2.0.0 on Windows, on Bazel CI:

https://buildkite.com/bazel/bazel-bazel-examples/builds/311#bd238f11-740a-4370-ad76-803852013ba5

```

(00:14:18) ERROR: D:/b/hdfb3qyi/external/maven/BUILD:86:1: Couldn't build file external/maven/com_android_support_appcompat_v7_symbols/symbols.zip: Compiling Android resources for @maven//:com_android_support_appcompat_v7 failed (Exit 1)
--
  | Jan 22, 2020 12:14:17 AM java.util.stream.ForEachOps$ForEachOp$OfRef accept
  | SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-hdpi-v4\abc_textfield_default_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-hdpi-v4\abc_textfield_default_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-hdpi-v4\abc_textfield_default_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | Jan 22, 2020 12:14:17 AM java.util.stream.ForEachOps$ForEachOp$OfRef accept
  | SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_list_divider_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_list_divider_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_list_divider_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | Jan 22, 2020 12:14:17 AM java.util.stream.ForEachOps$ForEachOp$OfRef accept
  | SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_scrubber_track_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_scrubber_track_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_scrubber_track_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | Jan 22, 2020 12:14:17 AM java.util.stream.ForEachOps$ForEachOp$OfRef accept
  | SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | Jan 22, 2020 12:14:17 AM java.util.stream.ForEachOps$ForEachOp$OfRef accept
  | SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_list_divider_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_list_divider_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_list_divider_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | Jan 22, 2020 12:14:17 AM java.util.stream.ForEachOps$ForEachOp$OfRef accept
  | SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_scrubber_primary_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_scrubber_primary_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_scrubber_primary_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | Exception in thread "main" com.google.devtools.build.android.aapt2.ResourceCompiler$CompileError
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileError.of(ResourceCompiler.java:110)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompilingVisitor.getCompiledArtifacts(ResourceCompiler.java:422)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler.getCompiledArtifacts(ResourceCompiler.java:456)
  | at com.google.devtools.build.android.UnvalidatedAndroidData.compile(UnvalidatedAndroidData.java:103)
  | at com.google.devtools.build.android.CompileLibraryResourcesAction.main(CompileLibraryResourcesAction.java:140)
  | at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$10.call(ResourceProcessorBusyBox.java:120)
  | at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
  | at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:198)
  | Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-hdpi-v4\abc_textfield_default_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-hdpi-v4\abc_textfield_default_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-hdpi-v4\abc_textfield_default_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
  | at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:226)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:173)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:120)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
  | at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  | at java.base/java.lang.Thread.run(Thread.java:834)
  | Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_list_divider_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_list_divider_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_list_divider_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
  | at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:226)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:173)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:120)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
  | at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  | at java.base/java.lang.Thread.run(Thread.java:834)
  | Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_scrubber_track_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_scrubber_track_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_scrubber_track_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
  | at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:226)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:173)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:120)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
  | at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  | at java.base/java.lang.Thread.run(Thread.java:834)
  | Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
  | at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:226)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:173)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:120)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
  | at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  | at java.base/java.lang.Thread.run(Thread.java:834)
  | Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_list_divider_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_list_divider_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_list_divider_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
  | at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:226)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:173)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:120)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
  | at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  | at java.base/java.lang.Thread.run(Thread.java:834)
  | Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_scrubber_primary_mtrl_alpha.9.png:
  | Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
  | compile\
  | -v\
  | --legacy\
  | -o\
  | D:\temp\android_resources_tmp632513122984622880\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_scrubber_primary_mtrl_alpha.9.png
  | Output:
  | bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\com_android_support_appcompat_v7\res\drawable-xxhdpi-v4\abc_scrubber_primary_mtrl_alpha.9.png: note: compiling PNG.
  |  
  | at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
  | at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:226)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:173)
  | at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:120)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
  | at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
  | at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  | at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jin** [comment]
Can also reproduce with Bazel 1.0.0 (see https://github.com/bazelbuild/rules_jvm_external/issues/364#issuecomment-581539406)
