### ISSUE TITLE
UnsatisfiedLinkError occurs in com.example.android.bazel.

### ISSUE THREAD

**Issue by H1Gdev** [bazelbuild/examples#171]
### Do the following:

1. `$ cd android/ndk/`
1. `$ bazel mobile-install //app/src/main:app --fat_apk_cpu=armeabi-v7a,arm64-v8a,x86,x86_64 --start_app`

### The following exception occurs.

```
05-18 22:16:48.039 10071 10071 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.example.android.bazel.MainActivity.stringFromJNI() (tried Java_com_example_android_bazel_MainActivity_stringFromJNI and Java_com_example_android_bazel_MainActivity_stringFromJNI__)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at com.example.android.bazel.MainActivity.stringFromJNI(Native Method)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at com.example.android.bazel.MainActivity.onCreate(MainActivity.java:20)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7023)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7014)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6518)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-18 22:16:48.039 10071 10071 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Bazel

bazel 3.0.0

**Comment by H1Gdev** [comment]
I checked `libapp.so` using `readelf`, but there is no `Java_com_example_android_bazel_MainActivity_stringFromJNI`.

**Comment by H1Gdev** [comment]
Is it the same as #125 ?

**Comment by H1Gdev** [comment]
It isresolved by adding `alwayslink = 1`.
