### ISSUE TITLE
bazel-downstream-projects/examples/tutorial is failing on Bazel CI

### ISSUE THREAD

**Issue by ShreeM01** [bazelbuild/examples#260]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2703#01840dd3-504b-4eb5-b95a-6b15a7e62722

<img width="1536" alt="Screen Shot 2022-10-26 at 1 34 18 AM" src="https://user-images.githubusercontent.com/109167932/197976881-fb30e696-c349-4df0-8700-29c08fab7e26.png">

**Comment by sgowroji** [comment]
Adding the stack traces below 


```

ERROR: Traceback (most recent call last):
--
  | File "/var/lib/buildkite-agent/builds/bk-docker-j2dn/bazel-downstream-projects/examples/tutorial/WORKSPACE", line 72, column 28, in <toplevel>
  | java_appengine_repositories()
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/48c02305111692ce77dc8bcedc4eaa3b/external/io_bazel_rules_appengine/appengine/java_appengine.bzl", line 321, column 35, in java_appengine_repositories
  | bazel_version = tuple([int(n) for n in native.bazel_version.split(".")])
  | Error in int: invalid base-10 literal: "0rc1"
  | ERROR: error loading package 'external': Package 'external' contains errors
  | Traceback (most recent call last):
  | File "bazelci.py", line 3597, in <module>
  | sys.exit(main())
  | File "bazelci.py", line 3577, in main
  | bazel_version=task_config.get("bazel") or configs.get("bazel"),
  | File "bazelci.py", line 1292, in execute_commands
  | bazel_version = print_bazel_version_info(bazel_binary, platform)
  | File "bazelci.py", line 1535, in print_bazel_version_info
  | + ["--nosystem_rc", "--nohome_rc", "info"]
  | File "bazelci.py", line 2259, in execute_command
  | args, shell=shell, check=fail_if_nonzero, env=os.environ, cwd=cwd
  | File "/usr/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
  | subprocess.CalledProcessError: Command '['bazel', '--nosystem_rc', '--nohome_rc', 'info']' returned non-zero exit status 1.
  | 🚨 Error: The command exited with status 1
  | user command error: The plugin docker command hook exited with status 1


```

**Comment by meteorcloudy** [comment]
To be clear, this is failing with the 6.0 release rc1, which has version number `6.0.0rc1`

**Comment by alexeagle** [comment]
examples/tutorial was removed in #331
