### ISSUE TITLE
Examples do not build under Bazel 6

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/examples#277]
```
aryehh@aryehh ~/Development/code/examples
 % bazel build //...                                                                      
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 096687e2-7229-4ba9-aa60-bdba69e1c6ba
DEBUG: /usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
ERROR: Traceback (most recent call last):
	File "/usr/local/google/home/aryehh/Development/code/examples/bzlmod/02-override_bazel_module/BUILD", line 1, column 38, in <toplevel>
		load("@bazel_skylib//:version.bzl", "hello_msg")
Error: file '@bazel_skylib//:version.bzl' does not contain symbol 'hello_msg'
DEBUG: /usr/local/google/home/aryehh/Development/code/examples/bzlmod/06-specify_dev_dependency/BUILD:3:6: Bazel Skylib version: 1.2.1
INFO: Repository build_bazel_rules_android instantiated at:
  /usr/local/google/home/aryehh/Development/code/WORKSPACE.bazel:325:20: in <toplevel>
  /usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl:72:10: in kotlin_repositories
  /usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Skipping '//...': error loading package under directory '': error loading package 'examples/tutorial/backend': Unable to find package for @io_bazel_rules_appengine//appengine:appengine.bzl: The repository '@io_bazel_rules_appengine' could not be resolved: Repository '@io_bazel_rules_appengine' is not defined.
WARNING: Target pattern parsing failed.
ERROR: error loading package under directory '': error loading package 'examples/tutorial/backend': Unable to find package for @io_bazel_rules_appengine//appengine:appengine.bzl: The repository '@io_bazel_rules_appengine' could not be resolved: Repository '@io_bazel_rules_appengine' is not defined.
INFO: Elapsed time: 3.595s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (58 packages loaded)
    currently loading: frontend/planning/study/project/change/edit_change/new_line_change ... (109 packages)
aryehh@aryehh ~/Development/code/examples
 % bazel --version                                                                  
bazel 6.0.0
```

**Comment by aryeh-looker** [comment]
```
 % bazel-5.0.0 build //...
INFO: Invocation ID: 4a56cf7f-5c9e-4c6a-936c-23ecd99b4209
ERROR: Traceback (most recent call last):
	File "/usr/local/google/home/aryehh/Development/code/WORKSPACE.bazel", line 63, column 23, in <toplevel>
		remote_java_repository(
	File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/bazel_tools/tools/jdk/remote_java_repository.bzl", line 34, column 5, in remote_java_repository
		def remote_java_repository(name, version, exec_compatible_with, prefix = "remotejdk", **kwargs):
Error: remote_java_repository() missing 1 required positional argument: exec_compatible_with
ERROR: error loading package '': Encountered error while reading extension file 'buf/repositories.bzl': no such package '@rules_buf//buf': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.086s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by aryeh-looker** [comment]
```
 % bazel-5.1.0 build //...
INFO: Invocation ID: 51a5296e-76cd-48c1-92da-6b9386703cd7
ERROR: Traceback (most recent call last):
	File "/usr/local/google/home/aryehh/Development/code/WORKSPACE.bazel", line 63, column 23, in <toplevel>
		remote_java_repository(
	File "/usr/local/google/home/aryehh/.cache/bazel/_bazel_aryehh/d115293f84f1332379fb52a513faaa5c/external/bazel_tools/tools/jdk/remote_java_repository.bzl", line 34, column 5, in remote_java_repository
		def remote_java_repository(name, version, exec_compatible_with, prefix = "remotejdk", **kwargs):
Error: remote_java_repository() missing 1 required positional argument: exec_compatible_with
ERROR: error loading package '': Encountered error while reading extension file 'buf/repositories.bzl': no such package '@rules_buf//buf': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.122s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by aryeh-looker** [comment]
```
 % uname -a       
Linux aryehh.c.googlers.com 5.19.11-1rodete1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1rodete1 (2022-10-31) x86_64 GNU/Linux
```

**Comment by aryeh-looker** [comment]
```
 % uname -a       
Linux ... 5.19.11 ... x86_64 GNU/Linux
```

**Comment by alexeagle** [comment]
Which example(s) are you trying to build? Each top-level folder in this repo is an independent Bazel workspace so "repo does not build" doesn't make sense - it's not possible to run `bazel build` at the root of the repo.
