### ISSUE TITLE
Bazel ios example is failing at Bazel@HEAD in downstream CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/examples#288]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2997#0187e486-4407-4dd3-b26b-2b14c15c9513

Platform : Bazel Examples (tutorials (Bazel end-to-end example) on :mac: (OpenJDK 11, Xcode))
```
ERROR: /Users/sgowroji/bazelci/bazelhead_downstream/bazelexamples/examples/tutorial/ios-app/BUILD:19:16: in ios_application rule //ios-app:ios-app: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_sgowroji/55b23971106c4338d22f304092da2c92/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 187, column 66, in _ios_application_impl
		debug_outputs = linking_support.debug_outputs_by_architecture(link_result.outputs)
	File "/private/var/tmp/_bazel_sgowroji/55b23971106c4338d22f304092da2c92/external/build_bazel_rules_apple/apple/internal/linking_support.bzl", line 45, column 68, in _debug_outputs_by_architecture
		bitcode_symbol_maps[link_output.architecture] = link_output.bitcode_symbols
Error: 'apple_linking_output' value has no field or method 'bitcode_symbols'
Available attributes: architecture, binary, dsym_binary, environment, linkmap, platform
ERROR: /Users/sgowroji/bazelci/bazelhead_downstream/bazelexamples/examples/tutorial/ios-app/BUILD:19:16: Analysis of target '//ios-app:ios-app' failed
ERROR: Analysis of target '//ios-app:ios-app' failed; build aborted: 
```

Steps followed :  
1. git clone https://github.com/bazelbuild/examples.git 
2. git reset c1d0fccc51dffc162bd8f3a2f352cc0f27da2f72 --hard
3. export USE_BAZEL_VERSION=8087520b153832656695fef6f3654ed432642c98
4.  cd examples/tutorial/ios-app
5. bazel build //ios-app

CC @meteorcloudy

**Comment by meteorcloudy** [comment]
rules_apple needs to be fixed and updated first.
