### ISSUE TITLE
[Bug]: pnpm v9 lockfile issues for frontend examples

### ISSUE THREAD

**Issue by dkthezero** [bazelbuild/examples#464]
Reproduce:
  - Install pnpm v9.2.0
  - Remove [pnpm-lock.yaml](https://github.com/bazelbuild/examples/blob/main/frontend/pnpm-lock.yaml)
  - Run `pnpm install`
  - Run `pnpm run build`

Then the error occur:
```
Repository rule npm_translate_lock_rule defined at:
  /private/var/tmp/_bazel_dkthezero/f3a599e6e224858962c4e41ca1d729db/external/aspect_rules_js~/npm/private/npm_translate_lock.bzl:145:42: in <toplevel>
ERROR: An error occurred during the fetch of repository 'aspect_rules_js~~npm~npm':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_dkthezero/f3a599e6e224858962c4e41ca1d729db/external/aspect_rules_js~/npm/private/npm_translate_lock.bzl", line 117, column 45, in _npm_translate_lock_impl
                helpers.verify_lifecycle_hooks_specified(rctx, state)
        File "/private/var/tmp/_bazel_dkthezero/f3a599e6e224858962c4e41ca1d729db/external/aspect_rules_js~/npm/private/npm_translate_lock_helpers.bzl", line 585, column 13, in _verify_lifecycle_hooks_specified
                fail("""\
Error in fail: ERROR: pnpm.onlyBuiltDependencies required in pnpm workspace root package.json when using pnpm v9 or later

As of pnpm v9, the lockfile no longer specifies if packages have lifecycle hooks.

Packages that rules_js should generate lifecycle hook actions for must now be declared in
pnpm.onlyBuiltDependencies in the pnpm workspace root package.json. See
https://pnpm.io/package_json#pnpmonlybuiltdependencies for more information.

Prior to pnpm v9, rules_js keyed off of the requiresBuild attribute in the pnpm lock
file to determine if a lifecycle hook action should be generated for an npm package.
See [pnpm #7707](https://github.com/pnpm/pnpm/issues/7707) for the reasons that pnpm
removed the requiredBuild attribute from the lockfile in v9.
```

Fix: Downgrade the pnpm to v8.15.8.
Expectation: can run with pnpm v9

**Comment by tbeamish-benchsci** [comment]
I'm seeing this issue with:
pnpm v9.1.0
bazel 7.3.1

What was the fix?

**Comment by lenhartd-apex** [comment]
Same issue with pnpm v9.12.2 and bazel 7.3.2

**Comment by jschaf** [comment]
The fix is to list which packages are allowed to execute during install:

https://pnpm.io/package_json#pnpmonlybuiltdependencies

**package.json**
```json
  "pnpm": {
    "onlyBuiltDependencies": ["fsevents"]
  }
```

**Comment by lenhartd-apex** [comment]
> The fix is to list which packages are allowed to execute during install:
> 
> https://pnpm.io/package_json#pnpmonlybuiltdependencies
> 
> **package.json**
> 
> ```json
>   "pnpm": {
>     "onlyBuiltDependencies": ["fsevents"]
>   }
> ```

Thanks @jschaf that's right. I did that also (and it works)

From the pnpm 9.x doc (your link):
> A list of package names that are allowed to be executed during installation. If this field exists, only the listed packages will be able to run install scripts.
