### ISSUE TITLE
[Bazel CI] Internal errors encountered during execution


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/examples#511]
CI: https://buildkite.com/bazel/bazel-bazel-examples/builds/3678#0192267a-a4bf-46b3-86fb-f03dc0986b42

 Platform: Ubuntu

 Logs: 
```
2024/09/25 00:05:09 could not download Bazel: failed to download bazel: failed to download bazel: could not copy from https://releases.bazel.build/7.2.1/release/bazel-7.2.1-linux-x86_64 to /var/lib/buildkite-agent/.cache/bazelisk/downloads/_tmp/download1332720524: stream error: stream ID 1; INTERNAL_ERROR; received from peer
Traceback (most recent call last):
  File "/workdir/bazelci.py", line 4529, in <module>
    sys.exit(main())
  File "/workdir/bazelci.py", line 4497, in main
    execute_commands(
  File "/workdir/bazelci.py", line 1302, in execute_commands
    PrepareRepoInCwd(True, initial_setup=True)
  File "/workdir/bazelci.py", line 1290, in PrepareRepoInCwd
    os.environ["OUTPUT_BASE"] = get_output_base(bazel_binary)
  File "/workdir/bazelci.py", line 2081, in get_output_base
    return execute_command_and_get_output(
  File "/workdir/bazelci.py", line 2689, in execute_command_and_get_output
    process = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'info', 'output_base']' returned non-zero exit status 1.
🚨 Error: The command exited with status 1
``` 

 CC Greenteam @comius @meteorcloudy

**Comment by meteorcloudy** [comment]
For those kind of errors, you can usually try to retry first.
