### ISSUE TITLE
Not able to build the android-ndk example

### ISSUE THREAD

**Issue by ychen404** [bazelbuild/examples#69]
Hi, 

I am having difficulties building the android-ndk example. 
Android SDK: 27.0.3
NDK version: R14b
Operating system: Ubuntu 16.04

Following is the error message. 
ERROR: /home/yitao/.cache/bazel/_bazel_yitao/2e4a3bcbc24ccbd22986f56e063d359f/external/com_android_support_appcompat_v7_26_1_0/BUILD:7:1: Validating Android resources for @com_android_
support_appcompat_v7_26_1_0//:com_android_support_appcompat_v7_26_1_0 failed (Exit 1)
Error: /tmp/resource_validator_tmp6621564669915564245/tmp-expanded/res/values-v26/values.xml:17: error: Error: No resource found that matches the given name: attr 'android:keyboardNavi
gationCluster'.

Any help is appreciated!

Best,
Yitao

**Comment by jin** [comment]
What's your Bazel version? I am not able to reproduce this with Bazel 0.15.2 on Ubuntu.

**Comment by ychen404** [comment]
I am using 15.0.2

**Comment by jin** [comment]
Could you please try `bazel clean --expunge && bazel build //app/src/main:app`?

**Comment by ychen404** [comment]
yitao@lab:android-ndk$ bazel15 clean --expunge && bazel build //app/src/main:app
Starting local Bazel server and connecting to it...
.......
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
.......
ERROR: /home/yitao/workspace/examples/android-ndk/app/src/main/BUILD.bazel:7:16: in manifest attribute of android_library rule //app/src/main:lib: The manifest must be called 'AndroidManifest.xml'.
ERROR: Analysis of target '//app/src/main:app' failed; build aborted.

It's strange. I didn't touch the manifest file at all and I checked the name is correct. 
Here is what the directory examples/android-ndk/app/src/mainlooks like:
AndroidManifest.xml  BUILD.bazel  cpp  java  LibraryManifest.xml  res

**Comment by jin** [comment]
That's a really old Bazel error. Are you sure you are using 0.15.2? What's the output of `bazel info version`?

**Comment by ychen404** [comment]
Following is the full error message. 

yitao@lab:main$ which bazel15 
/home/yitao/Downloads/bazel-0.15.2/output//bazel

yitao@lab:main$ bazel15 build //app/src/main:app
INFO: Analysed target //app/src/main:app (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/yitao/workspace/examples/android-ndk/app/src/main/BUILD.bazel:3:1: Validating Android resources for //app/src/main:lib failed (Exit 1)
Error: /tmp/resource_validator_tmp8120607333701206253/tmp-expanded/res/values-v26/values.xml:17: error: Error: No resource found that matches the given name: attr 'android:keyboardNav$
gationCluster'.
Error: 
Jul 25, 2018 4:59:27 PM com.google.devtools.build.android.AndroidResourceValidatorAction main
SEVERE: Unexpected
com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary package -f --no-crunch --no-version-vectors -I external/androidsdk/platforms/android-25/android.jar -M /tmp/resource_validat$
r_tmp8120607333701206253/manifest-aapt-dummy/AndroidManifest.xml -S /tmp/resource_validator_tmp8120607333701206253/tmp-expanded/res -A /tmp/resource_validator_tmp8120607333701206253/t$
p-expanded/assets -m -J /tmp/resource_validator_tmp8120607333701206253/generated_resources --output-text-symbols /tmp/resource_validator_tmp8120607333701206253/generated_resources -F $
azel-out/android-armeabi-v7a-fastbuild/bin/app/src/main/lib_files/library.ap_ --debug-mode --custom-package com.example.android.bazel --non-constant-id -0 apk
Error Code:
        1
Output:

Error at 17 : /tmp/resource_validator_tmp8120607333701206253/tmp-expanded/res/values-v26/values.xml:17: error: Error: No resource found that matches the given name: attr 'android:keyb$
ardNavigationCluster'.
12      :  <item name="colorError">?android:attr/colorError</item>
13      :  </style>
14      :  <style name="Base.V26.Widget.AppCompat.Toolbar" parent="Base.V7.Widget.AppCompat.Toolbar">
15      :  <item name="android:touchscreenBlocksFocus">true</item>
16      :  <item name="android:keyboardNavigationCluster">true</item>
17      :  </style>
18      :  <style name="Base.Widget.AppCompat.Toolbar" parent="Base.V26.Widget.AppCompat.Toolbar">
19      :  </style>
20      :  </resources>


        at com.google.devtools.build.android.AndroidResourceProcessor.runAapt(AndroidResourceProcessor.java:428)
        at com.google.devtools.build.android.AndroidResourceValidatorAction.main(AndroidResourceValidatorAction.java:155)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$2.call(ResourceProcessorBusyBox.java:66)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:193)

Exception in thread "main" com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        bazel-out/host/bin/external/androidsdk/aapt_binary package -f --no-crunch --no-version-vectors -I external/androidsdk/platforms/android-25/android.jar -M /tmp/resource_validat$r_tmp8120607333701206253/manifest-aapt-dummy/AndroidManifest.xml -S /tmp/resource_validator_tmp8120607333701206253/tmp-expanded/res -A /tmp/resource_validator_tmp8120607333701206253/t$p-expanded/assets -m -J /tmp/resource_validator_tmp8120607333701206253/generated_resources --output-text-symbols /tmp/resource_validator_tmp8120607333701206253/generated_resources -F $azel-out/android-armeabi-v7a-fastbuild/bin/app/src/main/lib_files/library.ap_ --debug-mode --custom-package com.example.android.bazel --non-constant-id -0 apk
Error Code:
        1
Output:

Error at 17 : /tmp/resource_validator_tmp8120607333701206253/tmp-expanded/res/values-v26/values.xml:17: error: Error: No resource found that matches the given name: attr 'android:keybo
ardNavigationCluster'.
12      :  <item name="colorError">?android:attr/colorError</item>
13      :  </style>
14      :  <style name="Base.V26.Widget.AppCompat.Toolbar" parent="Base.V7.Widget.AppCompat.Toolbar">
15      :  <item name="android:touchscreenBlocksFocus">true</item>
16      :  <item name="android:keyboardNavigationCluster">true</item>
17      :  </style>
18      :  <style name="Base.Widget.AppCompat.Toolbar" parent="Base.V26.Widget.AppCompat.Toolbar">
19      :  </style>
20      :  </resources>


        at com.google.devtools.build.android.AndroidResourceProcessor.runAapt(AndroidResourceProcessor.java:428)
        at com.google.devtools.build.android.AndroidResourceValidatorAction.main(AndroidResourceValidatorAction.java:155)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$2.call(ResourceProcessorBusyBox.java:66)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:193)
Target //app/src/main:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.409s, Critical Path: 1.11s
INFO: 3 processes: 3 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by jin** [comment]
Could you try changing this line
https://github.com/bazelbuild/examples/blob/2a1cede722ee45fee60a430b96af3324a1ac144d/android-ndk/app/src/main/BUILD.bazel#L11

to `gmaven_artifact("com.android.support:appcompat-v7:aar:27.1.0")`?

**Comment by ychen404** [comment]
ERROR: /home/yitao/.cache/bazel/_bazel_yitao/2e4a3bcbc24ccbd22986f56e063d359f/external/com_android_support_support_core_ui_27_1_0/BUILD:7:1: Merging Android resources for @com_android_support_support_core_ui_27_1_0//:com_android_support_support_core_ui_27_1_0 failed (Exit 1)
Jul 25, 2018 5:21:51 PM com.google.devtools.build.android.AndroidResourceMergingAction main
SEVERE: Error during merging resources
com.google.devtools.build.android.AndroidResourceMerger$MergingException: Error during merging
        at com.google.devtools.build.android.AndroidResourceMerger$MergingException.wrapException(AndroidResourceMerger.java:45)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:104)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:195)
        at com.google.devtools.build.android.AndroidResourceMergingAction.main(AndroidResourceMergingAction.java:256)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:96)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:193)
Caused by: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: fontStyle
        at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:99)
        at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeData(AndroidResourceMerger.java:94)
        ... 4 more
Caused by: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: fontStyle
        at com.google.devtools.build.android.AndroidFrameworkAttrIdJar.getAttrId(AndroidFrameworkAttrIdJar.java:48)
        at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:454)
        at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:367)
        at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:91)
        ... 6 more

Jul 25, 2018 5:21:51 PM com.google.devtools.build.android.ResourceProcessorBusyBox main
SEVERE: Error during merging
Target //app/src/main:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.351s, Critical Path: 3.85s
INFO: 108 processes: 102 linux-sandbox, 6 worker.
FAILED: Build did NOT complete successfully
yitao@lab:android-ndk$

**Comment by jin** [comment]
Ah, that explains it.

**Comment by ychen404** [comment]
Do you mind telling me why the api_level has to be higher than 25?

**Comment by jin** [comment]
I believe the resource attributes `android:keyboardNavigationCluster` and `android:fontStyle` are added in API 26 or later, which is why it cannot find them in API 25.
